title: Ben W Hutchins
url: "https://benhutchmet.github.io"
#baseurl: "/researcher_BWH"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "index"
 - name: "Research"
   link: "research"
 - name: "Conferences"
   link: "conferences"
 - name: "Blog"
   link: "blog"
 - name: "CV"
   link: "BWH_cv_220324.pdf"
 - name: "Contact"
   link: "contact"

theme: jekyll-theme-minimal